spring.jpa.hibernate.ddl-auto=update
# AWS RDS connection
spring.datasource.url=jdbc:mysql://golfcourse-db.cjiqu8y2oirz.ca-central-1.rds.amazonaws.com:3306/golfcourse?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true